"""empty message

Revision ID: 0d8c2640416c
Revises: 51e2c29ad95
Create Date: 2019-12-07 21:01:47.787479

"""

# revision identifiers, used by Alembic.
revision = '0d8c2640416c'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('alt_email', sa.String(length=100), nullable=True),
    sa.Column('alt_phone_no', sa.String(length=100), nullable=True),
    sa.Column('phone_no', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('interview_rounds')
    op.drop_table('interviews')
    op.drop_table('enq_emp_details')
    op.drop_table('interviewers')
    op.drop_table('candidates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('alt_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('alt_phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notice_period', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ctc', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('exp_ctc', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resume_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('current_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('last_updated_by_hr_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('profile_picture_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_table('interviewers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('alt_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('alt_phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by_hr_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by_interviewer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('profile_picture_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_table('enq_emp_details',
    sa.Column('sno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payroll_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hire_date', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('job_title_description', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('business_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('business_unit_description', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('home_department_description', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('account', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('practice_lead', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reporting_lead', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('delivery_lead', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('position_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('location_description', sa.VARCHAR(length=40), autoincrement=False, nullable=True)
    )
    op.create_table('interviews',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hr_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('interviewer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by_hr_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by_interviewer_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('interview_rounds',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('interview_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('interviewer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ratings', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('round_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('round_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by_hr_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by_interviewer_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_table('hr')
    # ### end Alembic commands ###
