"""empty message

Revision ID: 50d0c113c36b
Revises: 94c64945bf77
Create Date: 2019-12-15 19:42:34.008188

"""

# revision identifiers, used by Alembic.
revision = '50d0c113c36b'
down_revision = '94c64945bf77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
