"""empty message

Revision ID: 6513964691d4
Revises: 80856cd94229
Create Date: 2019-12-15 18:54:16.102590

"""

# revision identifiers, used by Alembic.
revision = '6513964691d4'
down_revision = '80856cd94229'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
