"""empty message

Revision ID: 6c5ae867c737
Revises: 0d8c2640416c
Create Date: 2019-12-07 21:45:43.316247

"""

# revision identifiers, used by Alembic.
revision = '6c5ae867c737'
down_revision = '0d8c2640416c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
