"""empty message

Revision ID: 80856cd94229
Revises: b0af66e0f5d3
Create Date: 2019-12-15 18:52:28.840062

"""

# revision identifiers, used by Alembic.
revision = '80856cd94229'
down_revision = 'b0af66e0f5d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
