"""empty message

Revision ID: a8c872720fc5
Revises: 50d0c113c36b
Create Date: 2019-12-15 19:44:48.332216

"""

# revision identifiers, used by Alembic.
revision = 'a8c872720fc5'
down_revision = '50d0c113c36b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
