"""empty message

Revision ID: ade57258679d
Revises: a8c872720fc5
Create Date: 2019-12-15 19:46:45.199483

"""

# revision identifiers, used by Alembic.
revision = 'ade57258679d'
down_revision = 'a8c872720fc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_rounds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=True),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('ratings', sa.String(length=500), nullable=True),
    sa.Column('feedback', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=500), nullable=True),
    sa.Column('round_number', sa.BigInteger(), nullable=True),
    sa.Column('round_name', sa.String(length=500), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by_hr_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_rounds')
    # ### end Alembic commands ###
